version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    environment:
      CODACY_PROJECT_TOKEN: 8487e936bb8d4b3e8e4638c48dae1b10
    steps:
      - checkout
      - run: sudo pip install --upgrade pip
      - run: sudo pip install coverage
      - run: sudo pip install pytest
      - run: sudo pip install codacy-coverage
      - run: coverage run test.py
      - run: python3 -m pytest test/*.py --junitxml=test-reports/junit.xml
      - run: coverage xml --omit=test/*,test.py
      - run: python-codacy-coverage -r coverage.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

