version: 1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    environment:
      CODACY_PROJECT_TOKEN: 8487e936bb8d4b3e8e4638c48dae1b10
    steps:
      - checkout
      - run: sudo pip install --upgrade pip
      - run: sudo pip install coverage
      - run: sudo pip install codacy-coverage
      - run: coverage run test.py
      - run: coverage xml
      - run: python-codacy-coverage -r coverage.xml
