version: 1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install --upgrade pip
      - run: sudo pip install coverage
      - run: coverage run test.py
      - run: coverage report
